In [1]:
import pandas as pd

In [2]:
def test( x ):
    if x < 0: return '-'
    if x == 0: return '0'
    
    return '+'

df = pd.read_csv( 'testing_dataset.csv' )

In [3]:
df[ 'score_change' ] = df[ 'score_change' ].transform( test )
df

,d0,d1,d2,d3,d4,d5,r15,r30,r45,r60,r75,r90,score_change
0,32.202484,44.418465,55.226805,64.350602,71.344236,71.867934,0,0,2,3,7,8,+
1,17.464249,50.960769,56.462377,64.404969,86.127812,94.936821,0,1,1,3,4,5,+
2,33.105891,53.535035,62.968246,64.404969,66.910388,72.173402,0,0,1,2,6,9,+
3,28.653098,31.256999,56.639209,57.140179,61.911227,62.968246,0,1,2,4,7,11,-
4,61.911227,80.049984,85.510233,88.543774,91.547802,106.018866,0,0,0,0,1,4,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5236,25.612497,39.560081,56.859476,60.415230,63.031738,72.567210,0,1,2,3,6,9,-
5237,28.284271,63.007936,75.742986,91.443972,98.994949,101.316336,0,1,1,1,2,3,-
5238,33.600595,62.936476,79.202273,83.150466,88.955045,90.255194,0,0,1,1,2,5,-
5239,33.015148,44.687806,55.443665,58.796258,62.936476,84.386018,0,0,2,4,5,7,-
5240,29.000000,37.643060,43.829214,45.276926,57.428216,67.230945,0,1,3,5,7,8,-

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold, cross_val_score

cv_method = RepeatedStratifiedKFold( n_splits = 5, n_repeats = 1, random_state = 0 )

estimator = KNeighborsClassifier( n_neighbors = 3 )

cross_val_score( 
    estimator, 
    df.drop( columns = [ 'score_change' ] ), 
    df.score_change, 
    cv = cv_method, 
    scoring = 'accuracy' ).mean()

0.5727936093262213